name: domain_models
description: a package that contains the domain models for the app
version: 1.0.0
environment:
  sdk: ^3.3.3
dependencies:
  equatable: ^2.0.5
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
