name: sign_in
description: "A feature module for sign in"
version: 0.0.1
homepage: "none"
publish_to: "none"
environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  component_library:
    path: ../../component_library
  form_fields:
    path: ../../form_fields
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  user_repository:
    path: ../../user_repository
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
