name: bootcamp_repository
description: A sample command-line application.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.3.3
dependencies:
  domain_models:
    path: ../domain_models
  camper_api:
    path: ../camper_api

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
