name: key_value_storage
description: a package that contains the key-value storage for the app backed by Hive
version: 1.0.0
environment:
  sdk: ^3.3.3
dependencies:
  hive: ^2.2.3
  path_provider: ^2.1.2
dev_dependencies:
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  lints: ^3.0.0
  test: ^1.24.0
