name: camper_api
description: a package that contains the API client for the app
version: 1.0.0
environment:
  sdk: ^3.3.3
dependencies:
  dio: ^5.4.2+1
  json_annotation: ^4.8.1
dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
