name: component_library
description: a package that contains the shared components for the app
version: 0.0.1
homepage: none
environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
